version: "3.7"
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: docker.io/znmeb/postgis
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST_PORT}:5435
    volumes:
      - ${SHARED_WORK_AREA}:/Work
  rstats:
    build:
      context: .
      dockerfile: Dockerfile.rstats
    image: docker.io/znmeb/rstats
    environment:
      - PASSWORD=${RSTUDIO_PASSWORD}
    ports:
            - 8787:8787
            - 8888:8888
    volumes:
      - ${SHARED_WORK_AREA}:/Work
      - ${HOME}:/home/rstudio
      - /var/run/docker.sock:/var/run/docker.sock
  pgadmin4:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin4
    image: docker.io/znmeb/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
            - 8686:8686
    volumes:
      - ${SHARED_WORK_AREA}:/Work
