version: "3.7"
services:
  rstats:
    build:
      context: .
      dockerfile: Dockerfile.rstats
    image: docker.io/znmeb/rstats
    environment:
      - PASSWORD=${RSTUDIO_PASSWORD}
    ports:
            - 8787:8787
            - 8888:8888
    volumes:
      - ${SHARED_WORK_AREA}:/Work
      - ${HOME}:/home/rstudio
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
